{#- Reference: https://github.com/MetaCubeX/Clash.Meta/blob/Meta/docs/config.yaml -#}
port: 8080
socks-port: 1080

global-client-fingerprint: chrome

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]

dns:
  enable: true
  prefer-h3: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://223.5.5.5/dns-query
  fallback:  # IP addresses who is outside CN in GEOIP will fallback here
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true  # Enable GEOIP-based fallback
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.twitter.com'

proxies:
{{ get_nodes(type = "clash meta") | insert_indents(spaces = 2, include_first_line = true) }}
proxy-groups:
  - type: select
    name: Proxy
    proxies:
      - DIRECT
{%- for node_name in get_nodes_names(type = "clash meta") %}
      - {{ node_name -}}
{% endfor %}

rules:
  {# LAN -#}
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  {# Final -#}
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
