{#- Reference: https://github.com/Dreamacro/clash/wiki/Configuration -#}
port: 8080
socks-port: 1080
dns:
  enable: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://223.5.5.5/dns-query
  fallback:  # IP addresses who is outside CN in GEOIP will fallback here
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true  # Enable GEOIP-based fallback
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.twitter.com'

proxies:
{{ get_nodes(type = "clash") | insert_indents(spaces = 2, include_first_line = true) }}
proxy-groups:
  - type: select
    name: Proxy
    proxies:
      - DIRECT
{%- for node_name in get_nodes_names() %}
      - {{ node_name -}}
{% endfor %}

rules:
  {# LAN -#}
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  {# Final -#}
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
