name: Build Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.69
        with:
          targets: ${{ matrix.target }}

      - name: Install Cross
        run: cargo install cross

      - name: Build ${{ matrix.target }}
        timeout-minutes: 60
        run: cross build --target ${{ matrix.target }} --release

      - name: Make Tarball
        run: |
          mv target/${{ matrix.target }}/release/ringer ringer
          XZ_OPT=-e9 tar caf ringer_${{  github.ref_name }}_${{ matrix.target }}.tar.xz ringer

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ringer_${{  github.ref_name }}_${{ matrix.target }}.tar.xz

  release-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install GNU tar
        run: |
          brew install gnu-tar
          echo '/usr/local/opt/gnu-tar/libexec/gnubin' >> $GITHUB_PATH

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.69
        with:
          targets: aarch64-apple-darwin

      - name: Build
        timeout-minutes: 60
        run: cargo build --release && cargo build --release --target=aarch64-apple-darwin

      - name: Make Tarball
        run: |
          mv target/release/ringer ringer
          XZ_OPT=-e9 tar caf ringer_${{  github.ref_name }}_x86_64-apple-darwin.tar.xz ringer
          mv target/aarch64-apple-darwin/release/ringer ringer
          XZ_OPT=-e9 tar caf ringer_${{  github.ref_name }}_aarch64-apple-darwin.tar.xz ringer

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ringer_${{  github.ref_name }}_x86_64-apple-darwin.tar.xz
            ringer_${{  github.ref_name }}_aarch64-apple-darwin.tar.xz

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.69

      - name: Build
        timeout-minutes: 60
        run: cargo build --release

      - name: Make Tarball
        run: |
          mv target/release/ringer.exe ringer.exe
          7z a -t7z -mx=9 ringer_${{  github.ref_name }}_x86_64-pc-windows-msvc.7z ringer.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ringer_${{  github.ref_name }}_x86_64-pc-windows-msvc.7z
